# -*- coding: utf-8 -*-
"""easy-uiauto - UI automation toolkit based on pyautogui and uiautomation"""

__version__ = "0.1.8"
__author__ = "Poggi-Tang"

from .ctrl import (
    Controller,
    activate_window,
    centre_click,
    double_click,
    drag_control,
    drag_control_by_control,
    expand_collapse_control,
    input_text,
    key_click,
    key_group,
    key_press,
    key_release,
    left_click,
    mouse_left_press,
    mouse_left_release,
    mouse_move_control,
    mouse_move_pos,
    mouse_right_press,
    mouse_right_release,
    right_click,
    run_action,
    scroll,
    select_control,
    set_text,
    toggle_control,
)
from .draw import ScreenLineBox
from .record import RecordThread, run_record
from .utils import (
    auto_scroll,
    compile_controls,
    find_control,
    find_control_by_xpath,
    get_control_info,
    get_control_xpath,
    push_message,
    set_top_window,
)

__all__ = [
    "Controller",
    "left_click",
    "right_click",
    "double_click",
    "centre_click",
    "mouse_left_press",
    "mouse_left_release",
    "mouse_right_press",
    "mouse_right_release",
    "mouse_move_pos",
    "mouse_move_control",
    "drag_control",
    "drag_control_by_control",
    "set_text",
    "input_text",
    "key_click",
    "key_press",
    "key_release",
    "key_group",
    "activate_window",
    "run_action",
    "scroll",
    "select_control",
    "toggle_control",
    "expand_collapse_control",
    "run_record",
    "RecordThread",
    "find_control",
    "find_control_by_xpath",
    "get_control_info",
    "get_control_xpath",
    "compile_controls",
    "push_message",
    "set_top_window",
    "auto_scroll",
    "ScreenLineBox",
]
