name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
    branches:
      - main

permissions:
  id-token: write

jobs:
  publish:
    if: github.event_name == 'push' && github.event.head_commit.message == 'chore(release): publish v0.7.5'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/easy-uiauto

    steps:
      - uses: actions/checkout@v4
        with:
          ref: eaec137218a07970005e1e411a577d69268ce2d6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: python -m pip install --upgrade pip build

      - name: Build
        run: python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
